# Generated by Django 2.0.13 on 2019-08-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190812_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='organisation',
        ),
        migrations.AddField(
            model_name='organisation',
            name='client',
            field=models.ForeignKey(blank=True, default=None, on_delete='cascade', related_name='client_organization', to='client.Client'),
        ),
    ]
