# Generated by Django 2.0.13 on 2019-10-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('accountant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountant_note', to='accountant.Accountant')),
            ],
        ),
    ]
