# Generated by Django 2.0.13 on 2019-07-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20190730_1216'),
        ('accountant', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_many', to='accountant.Accountant')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_compny', to='client.Client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_many', to='manager.Manager')),
            ],
        ),
    ]
