# Generated by Django 2.0.13 on 2019-07-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
        ('client', '0002_auto_20190730_1216'),
        ('manager', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Task',
        ),
    ]
