# Generated by Django 2.0.13 on 2019-08-14 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190814_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accountant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountant_many', to='accountant.Accountant'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_many', to='manager.Manager'),
        ),
    ]
