# Generated by Django 2.0.13 on 2019-08-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190814_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='task',
            field=models.ForeignKey(blank=True, default=None, on_delete='cascade', related_name='task_file', to='task.Task'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_client', to='client.Client'),
        ),
    ]
