# Generated by Django 2.0.13 on 2019-08-16 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190815_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
