# Generated by Django 2.0.13 on 2019-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_historicaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
