# Generated by Django 2.0.13 on 2019-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20191003_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
