# Generated by Django 2.0.13 on 2019-12-26 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20191210_1406'),
        ('manager', '0001_initial'),
        ('client', '0005_auto_20190813_0740'),
        ('accountant', '0002_note'),
        ('task', '0016_auto_20191203_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('repeated_type', models.IntegerField(blank=True, null=True)),
                ('repeated_value', models.IntegerField(blank=True, null=True)),
                ('accountant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountant_repeated', to='accountant.Accountant')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_repeated', to='client.Client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_repeated', to='company.Company')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_repeated', to='manager.Manager')),
            ],
        ),
    ]
