# Generated by Django 2.0.13 on 2019-12-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_repeated'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='repeated',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.Repeated'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_repeated', to='task.Repeated'),
        ),
    ]
