# Generated by Django 2.0.13 on 2020-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20191226_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeated',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
