# Generated by Django 2.0.13 on 2020-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_repeated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeated',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
