# Generated by Django 2.0.13 on 2019-07-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('accountant', '0001_initial'),
        ('client', '0002_auto_20190730_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('accountant', models.ManyToManyField(null=True, related_name='accountant_many_company', to='accountant.Accountant')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.Client')),
                ('subscribe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='utils.Subscribe')),
            ],
        ),
    ]
