# Generated by Django 2.0.13 on 2019-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accountant',
            field=models.ManyToManyField(related_name='accountant_many_company', to='accountant.Accountant'),
        ),
    ]
