# Generated by Django 2.0.13 on 2019-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190813_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='HVHH',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='accountant',
            field=models.ManyToManyField(blank=True, null=True, related_name='accountant_many_company', to='accountant.Accountant'),
        ),
    ]
