# Generated by Django 2.0.13 on 2019-10-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_social'),
        ('company', '0005_auto_20191004_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='packages_company', to='utils.Packages'),
        ),
    ]
