# Generated by Django 2.0.13 on 2019-10-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_deleted_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
