# Generated by Django 2.0.13 on 2019-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20191017_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type_of_activity',
        ),
        migrations.AddField(
            model_name='company',
            name='type_of_activity',
            field=models.ManyToManyField(blank=True, null=True, to='company.TypeOfActivity'),
        ),
    ]
