# Generated by Django 2.0.13 on 2019-08-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
