# Generated by Django 2.0.13 on 2019-08-05 11:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20190805_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
