# Generated by Django 2.0.13 on 2019-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20190805_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='service',
            field=models.ManyToManyField(related_name='service_many', to='utils.CardService', verbose_name='service_many'),
        ),
    ]
