# Generated by Django 2.0.13 on 2019-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20190806_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
