# Generated by Django 2.0.13 on 2019-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20190812_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
